### ISSUE TITLE
add the opposite blockstate + add documentation and/or example

### ISSUE THREAD

**Issue by mxKeaton** [MikiP98/Boe-s-Earth#1]
Hey!
Just saw your mod on Modrinth. This is very close to what I was looking for a few months back. I am dissapointed, that vanilla features no `snow layer on top` blockstate, which I needed it to add some snowy leave textures. As I understand it right now, your mod does add the opposite and gives snow access to a blockstate of `leaves below`. Is there a way you could integrate the opposing blockstate as well?

Also, this would still be very useful for making the snow wave in the shader I am using, but the issue is, that I have no clue how to implement it properly and would love to see an example and/or a documentation of a kind. I tried using Bliss shaders, because you called it compatible, but I had no luck with it.

**Comment by MikiP98** [comment]
Hi!

I can try to add `snow_on_top` blockstate to leaves after I finish adding the config and carpet support.

Also small clarification, the blockstate added to snow, vines and carpets is called `is_on_leaves` as in is it based no leaves, for snow and carpet it in fact does mean is snow below, but for vines it means if it is growing from leaves.

I've added documentation to the README, you can check it out, if you have any questions or suggestion on how can I improve it, feel free to tell me :)

As for Bliss, the support was officially added, but the Bliss version with the support did not have any public releases yet, there were also some conflicts with internal Bliss branches...
The only Bliss version you can download with the support in it is, [official main branch](https://github.com/X0nk/Bliss-Shader) and [my fork of the shader](https://github.com/MikiP98/Bliss-Shader/tree/main).
To add the support for any other Bliss version, you need to copy the `block.properties` file from the supported version to the unsupported one.

I hope this answers all your questions, feel free to ask if you have more

**Comment by MikiP98** [comment]
I guess you want to do something like that: https://www.reddit.com/r/Minecraft/comments/yj4juk/snowy_bushy_leaves/
I wounder though how was this done before

**Comment by MikiP98** [comment]
Done, I've added `snow_on_top` blockstate to leaves.  
Currently only to the GitHub version, but I will release a version on Modrinth soon

**Comment by MikiP98** [comment]
You want is_ice_on_top too?

**Comment by MikiP98** [comment]
New version released on Modrinth.  
I will close this issue, but feel free to reopen it or open new one if you want.  

Also if you're resourcepack with Boe's Earth support is/will be available on Modrinth, I can link it in the Boe's Earth if you would like to, as an example working resourcepack similar to how Bliss is linked
